### ISSUE TITLE
[Question] Don't support decorator ?

### ISSUE THREAD

**Issue by agileago** [vuejs/jsx-next#444]
### 💻 Sample code

```
9:45:05 AM [vite] Internal server error: unknown: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (6:3):

  4 |
  5 | class Model {
> 6 |   @IsPositive({ message: '必须为正整数' })
    |   ^
  7 |   @IsInt({ message: '必须为整数 ' })
  8 |   count: number = 0
  9 | }
  Plugin: vue-jsx
  File: /Users/jianhuaren/vite-antd/src/app.tsx
  4  |  
  5  |  class Model {
  6  |    @IsPositive({ message: '必须为正整数' })
     |    ^
  7  |    @IsInt({ message: '必须为整数 ' })
  8  |    count: number = 0
      at Object._raise (/Users/jianhuaren/vite-antd/node_modules/@babel/parser/lib/index.js:810:17)
      at Object.raiseWithData (/Users/jianhuaren/vite-antd/node_modules/@babel/parser/lib/index.js:803:17)
      at Object.expectOnePlugin (/Users/jianhuaren/vite-antd/node_modules/@babel/parser/lib/index.js:9995:18)

```

**Comment by lizhancheng** [comment]
meet the same question, is there any solution?

**Comment by FranklyCai** [comment]
这说的不就是没开启legacy选项吗？给@babel/plugin-proposal-decorators插件传legacy为true的选项就可以了，比如plugins: [['@babel/plugin-proposal-decorators', { legacy: true }]]

**Comment by a1444942531** [comment]
> 这说的不就是没开启legacy选项吗？给@babel/plugin-proposal-decorators插件传legacy为true的选项就可以了，比如vueJsx（{ babelPlugins： [['@babel/plugin-proposal-decorators'， { legacy： true }]] }）

我滴个龟龟 原来是这样写的啊

**Comment by Kenhuey** [comment]
> 这说的不就是没开启legacy选项吗？给@babel/plugin-proposal-decorators插件传legacy为true的选项就可以了，比如vueJsx({ babelPlugins: [['@babel/plugin-proposal-decorators', { legacy: true }]] })

Works, well done
